/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjetoJava;

public class App {
    //comentario de linha

    public static void main(String[] args) {
        System.out.println("hello worlds");
        System.out.println("meu seguno comando");
    }
}
